---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  Creates an ECR repository for the Avoca container images.

Parameters:
  DevUe1AvocaApiRepositoryName:
    Type: String
    Description: The name of the ECR repository, e.g. 'prod-api-container'
    Default: "dev-ue1-avoca-api-container"

  DevUe1AvocaCallsRepositoryName:
    Type: String
    Description: The name of the ECR repository, e.g. 'prod-api-container'
    Default: "dev-ue1-avoca-calls-container"

Resources:
  DevUe1AvocaApiContainerECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref DevUe1AvocaApiRepositoryName
      EmptyOnDelete: false
      EncryptionConfiguration:
        EncryptionType: AES256
        # KmsKey: String # Only necessary if using a custom KMS key
      ImageScanningConfiguration:
        ScanOnPush: false
      ImageTagMutability: IMMUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 1
                },
                "action": {
                    "type": "expire"
                }
              }
            ]
          }
  DevUe1AvocaCallsContainerECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref DevUe1AvocaCallsRepositoryName
      EmptyOnDelete: false
      EncryptionConfiguration:
        EncryptionType: AES256
        # KmsKey: String # Only necessary if using a custom KMS key
      ImageScanningConfiguration:
        ScanOnPush: false
      ImageTagMutability: IMMUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 1
                },
                "action": {
                    "type": "expire"
                }
              }
            ]
          }

Outputs:
  DevUe1AvocaApiContainerECRRepositoryUri:
    Description: "URI of the ECR repository"
    Value: !GetAtt
      - DevUe1AvocaApiContainerECRRepository
      - RepositoryUri
    Export:
      Name: DevUe1AvocaApiContainerECRRepositoryUri

  DevUe1AvocaCallsContainerECRRepositoryUri:
    Description: "URI of the ECR repository"
    Value: !GetAtt
      - DevUe1AvocaCallsContainerECRRepository
      - RepositoryUri
    Export:
      Name: DevUe1AvocaCallsContainerECRRepositoryUri
