FROM --platform=linux/amd64 node:22-alpine as builder

WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install

COPY . .
RUN npm run build

FROM --platform=linux/amd64 node:22-alpine
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install --omit=dev
COPY --from=builder /app/dist ./dist

EXPOSE 8080

CMD ["npm", "run", "start:dev"]